/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/polls/{pollId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить определение опроса
         * @description Иммутабельно с момента публикации (state != draft), поэтому отдаётся с агрессивным Cache-Control — предполагается, что в проде этот ответ обслуживает CDN, а не бэкенд напрямую (docs/ai/02-load-model.md §6.1). Опрос в состоянии draft не существует для внешнего мира — 404, чтобы не спойлерить вопрос до публикации.
         *
         *     Ответ намеренно не содержит `state`: он меняется в течение жизни опроса (scheduled → open → closed), а этот ответ кешируется на сутки как неизменяемый — поле, которое меняется, ломало бы саму предпосылку кеширования. Клиент определяет, идёт ли сейчас приём голосов, сравнивая текущее время с `opens_at`/`closes_at`; сервер остаётся единственным источником истины в момент самого запроса `POST /votes`, который не полагается на этот кеш.
         */
        get: operations["getPoll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/polls/{pollId}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выдать анонимный токен голосования
         * @description Первый шаг двухшагового флоу голосования (docs/ai/01-stack.md, раздел про k6): токен нужно получить один раз при открытии страницы, до отправки голоса. Токен — самоподписанный (HMAC-SHA256 над poll_id+expires_at+nonce, где expires_at = closes_at опроса на момент выдачи — не issued_at, иначе проверка на голосовании не закрывалась бы локально одним сравнением, см. docs/ai/05-api-contract.md), выдача не требует обращения к Redis — обращение к Redis происходит только при самом голосовании (проверка dedup-ключа), см. docs/ai/05-api-contract.md.
         *     Сервер одновременно ставит cookie `vote_token` (не HttpOnly — чтобы фронтенд мог продублировать значение в localStorage) и возвращает тот же токен в теле ответа, согласно схеме из docs/ai/01-stack.md («Граница с фронтендом», пункт 2).
         */
        post: operations["issueVoteToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/polls/{pollId}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Проголосовать
         * @description Единственный эндпоинт, который реально обслуживает бэкенд под пиковой нагрузкой (docs/ai/02-load-model.md §6.1). Токен принимается из cookie `vote_token` ИЛИ заголовка `X-Vote-Token` — сервер принимает любой из двух источников (docs/ai/01-stack.md). Ровно один голос на валидный токен: гонки разрешаются атомарным Lua-скриптом в Redis (docs/ai/01-stack.md, «Redis как горячий путь»).
         */
        post: operations["castVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/polls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список опросов */
        get: operations["listPolls"];
        put?: never;
        /** Создать опрос */
        post: operations["createPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/polls/{pollId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить опрос (админский вид, включая внутренние поля) */
        get: operations["getPollAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/polls/{pollId}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Перевести опрос в следующее состояние FSM
         * @description Единый эндпоинт для переходов draft → scheduled → open → closed (docs/ai/01-stack.md). Переход, не разрешённый текущим состоянием (например open → draft), — 409. `scheduled_at` обязателен только при переходе в scheduled.
         */
        post: operations["transitionPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/polls/{pollId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Обезличенные результаты опроса
         * @description Данные eventually consistent (docs/ai/02-load-model.md §6.6): значение — это снапшот, снятый воркером не более секунды назад, а не чтение "вживую" из Redis.
         */
        get: operations["getPollResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/polls/{pollId}/results/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Динамика голосования по времени
         * @description Строится из истории снапшотов в Postgres — побочный продукт схемы снапшотирования (docs/ai/01-stack.md, раздел про PostgreSQL).
         */
        get: operations["getPollResultsTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/warmup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Прогреть пулы соединений к Postgres и Redis перед эфиром
         * @description Вызывается оркестратором по расписанию эфира, не человеком (docs/ai/02-load-model.md §6.5): прескейлинг детерминирован сеткой вещания, а не реактивным автоскейлингом. Без тела — прогревает пулы в целом (по одному пингу на каждый слот пула Postgres/Redis, чтобы соединения были открыты заранее, а не лениво на первый реальный запрос пика); с `poll_id` — дополнительно принудительно подгружает определение опроса в кеш инстанса (используется голосованием и публичным `GET`) и пишет это в audit log.
         *     Загрузка Lua-скрипта здесь не нужна: горячий путь голосования не использует Lua — единственное обращение к Redis на голос это `SET NX GET`, корректность которого даёт атомарность самой команды, без серверного скрипта.
         */
        post: operations["warmup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness-проверка для docker-compose / оркестратора */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus-метрики
         * @description Формат exposition Prometheus. Минимальный набор метрик перечислен в docs/ai/01-stack.md (votes_accepted_total, votes_rejected_total{reason}, гистограмма латентности, redis_command_duration_seconds, inflight_requests).
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example invalid_option */
                code: string;
                message: string;
            };
        };
        /**
         * @description FSM опроса, docs/ai/01-stack.md.
         * @enum {string}
         */
        PollState: "draft" | "scheduled" | "open" | "closed";
        PollOption: {
            /** @description Порядковый номер варианта в опросе (1..N), не UUID — это хэш-поле на горячем пути голосования, см. docs/ai/04-data-model.md §1.2. */
            id: number;
            label: string;
        };
        PollOptionInput: {
            label: string;
        };
        PollDefinition: {
            /** Format: uuid */
            id: string;
            question: string;
            options: components["schemas"]["PollOption"][];
        };
        /** @description Намеренно без `state` — см. пояснение в description у GET /v1/polls/{pollId}. Любой опрос, для которого этот объект вообще отдаётся (не 404), уже прошёл scheduled, так что opens_at/closes_at всегда заполнены, не null. */
        PollPublic: components["schemas"]["PollDefinition"] & {
            /**
             * Format: date-time
             * @description Равно scheduled_at на момент публикации — единственный вход для closes_at (докрутка триггером в Postgres, docs/ai/04-data-model.md §1.1), поэтому оба поля иммутабельны и кешируемы уже с состояния scheduled, а не только с open.
             */
            opens_at: string;
            /**
             * Format: date-time
             * @description Дефолт длины окна — 5 минут (docs/ai/02-load-model.md §6.4), это НЕ длительность ролика. Фактическое открытие (переход в open) может случиться на секунды позже opens_at — на это значение не влияет, окно голосования фиксируется в момент планирования, а не в момент фактического старта.
             */
            closes_at: string;
        };
        PollAdmin: components["schemas"]["PollDefinition"] & {
            state: components["schemas"]["PollState"];
            /**
             * Format: date-time
             * @description Плановое время эфира — вход для /internal/warmup.
             */
            scheduled_at: string | null;
            /**
             * Format: date-time
             * @description Равно null, пока draft-опрос не запланирован.
             */
            opens_at: string | null;
            /**
             * Format: date-time
             * @description Равно null, пока draft-опрос не запланирован.
             */
            closes_at: string | null;
            /** @description Длина окна приёма голосов от момента open. По умолчанию 300с. */
            voting_window_seconds: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PollCreateRequest: {
            question: string;
            options: components["schemas"]["PollOptionInput"][];
            /**
             * Format: date-time
             * @description Если задано — опрос сразу создаётся в scheduled, а не draft.
             */
            scheduled_at?: string | null;
            /** @default 300 */
            voting_window_seconds: number;
        };
        PollTransitionRequest: {
            /**
             * @description Целевое состояние. draft недостижим как цель перехода — это только начальное состояние.
             * @enum {string}
             */
            to: "scheduled" | "open" | "closed";
            /**
             * Format: date-time
             * @description Обязательно при to=scheduled, игнорируется иначе.
             */
            scheduled_at?: string;
        };
        VoteToken: {
            /** @description Самоподписанный opaque-токен, см. docs/ai/05-api-contract.md. */
            token: string;
            /**
             * Format: date-time
             * @description Равен closes_at опроса на момент выдачи (не фиксированный сдвиг от issued_at) — иначе токен, выданный ближе к концу окна, либо переживает закрытие, либо протухает раньше времени. См. docs/ai/03-deduplication.md §2.3.
             */
            expires_at: string;
        };
        VoteRequest: {
            option_id: number;
        };
        VoteAccepted: {
            /** @enum {string} */
            status: "accepted";
            option_id: number;
        };
        VoteRejected: {
            /** @enum {string} */
            status: "rejected";
            /**
             * @description Совпадает со значениями метки reason у votes_rejected_total (docs/ai/01-stack.md).
             * @enum {string}
             */
            reason: "duplicate" | "closed" | "rate_limited";
            /** @description Присутствует только при reason=duplicate: вариант, который был засчитан первым (успешным) голосованием этим токеном. Позволяет клиенту, потерявшему ответ на первый POST и повторившему запрос тем же токеном, увидеть «уже засчитан вариант X» вместо голого конфликта — dedup-ключ в Redis хранит option_id, а не флаг (docs/ai/03-deduplication.md §2.1). */
            option_id?: number;
        };
        PollResults: {
            /** Format: uuid */
            poll_id: string;
            state: components["schemas"]["PollState"];
            total_accepted: number;
            /** @description Продуктовый сигнал накрутки: резкий рост доли duplicate во время эфира (docs/ai/01-stack.md, раздел про Prometheus-метрики). */
            rejected?: {
                duplicate?: number;
                rate_limited?: number;
            };
            options: {
                option_id: number;
                label: string;
                count: number;
                /** @description count / total_accepted, для удобства фронтенда админки. */
                share?: number;
            }[];
            /**
             * Format: date-time
             * @description Время снятия снапшота воркером, не "прямо сейчас" (eventually consistent). null, если опрос ещё не успел получить ни одного снапшота (открылся меньше секунды назад) — в этом случае total_accepted/options/rejected нулевые, а не отсутствуют.
             */
            snapshot_at: string | null;
            /** @description Прозрачность деградации уровня 2 (docs/ai/02-load-model.md §6.7): если сэмплирование когда-либо включалось для этого опроса, это обязано быть видно в результатах, а не только в логах. */
            sampling: {
                enabled: boolean;
                /** @description K в 'принимается 1 из K', null если sampling никогда не включался. */
                rate?: number | null;
            };
        };
        ResultsSnapshotPoint: {
            /** Format: date-time */
            at: string;
            total_accepted: number;
            options: {
                option_id: number;
                count: number;
            }[];
        };
    };
    responses: {
        /** @description Опрос не найден. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Отсутствует или неверен Bearer-токен администратора. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit превышен. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PollId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPoll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: components["parameters"]["PollId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Опрос найден и опубликован (scheduled/open/closed). */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollPublic"];
                };
            };
            /** @description Опрос не найден или ещё не опубликован (state=draft). `Cache-Control: no-store` — намеренно, в отличие от 200: без этого CDN мог бы закешировать 404 для опроса, который публикуется через секунду, и продолжать отдавать его уже после публикации. */
            404: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issueVoteToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: components["parameters"]["PollId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Токен выдан. */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteToken"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    castVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: components["parameters"]["PollId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description Голос принят и учтён в счётчике. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteAccepted"];
                };
            };
            /** @description Некорректный option_id (не существует в опросе). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Токен голосования отсутствует, просрочен или не проходит проверку подписи. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Голос отклонён: либо повторное голосование этим токеном (`reason=duplicate`), либо опрос сейчас не принимает голоса — draft/scheduled/closed (`reason=closed`). Соответствует меткам `votes_rejected_total{reason}` из docs/ai/01-stack.md. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteRejected"];
                };
            };
            /** @description Уровень 1 деградации (docs/ai/02-load-model.md §6.7): превышен лимит запросов. `Retry-After` намеренно содержит случайный разброс, чтобы клиенты не ретраили синхронно. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteRejected"];
                };
            };
            /** @description Уровень 3 деградации: Redis недоступен, приём голосов остановлен. Результаты по уже принятым голосам продолжают отдаваться через /results. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPolls: {
        parameters: {
            query?: {
                state?: components["schemas"]["PollState"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список опросов. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PollAdmin"][];
                        total: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PollCreateRequest"];
            };
        };
        responses: {
            /** @description Опрос создан в состоянии draft. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollAdmin"];
                };
            };
            /** @description Невалидный опрос (меньше 2 вариантов и т.п.). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPollAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: components["parameters"]["PollId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Опрос найден. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollAdmin"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    transitionPoll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: components["parameters"]["PollId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PollTransitionRequest"];
            };
        };
        responses: {
            /** @description Переход выполнен. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollAdmin"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Переход недопустим из текущего состояния. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPollResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: components["parameters"]["PollId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результаты. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResults"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPollResultsTimeseries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: components["parameters"]["PollId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Точки снапшотов, по возрастанию времени. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        points: components["schemas"]["ResultsSnapshotPoint"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    warmup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    poll_id?: string;
                };
            };
        };
        responses: {
            /** @description Прогрев запущен (асинхронно). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис жив. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Метрики в текстовом формате Prometheus. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
